export const modules = [
  {
    id: "m1",
    number: "01",
    title: "React foundations",
    subtitle: "Components, JSX, props and lists",
    concepts: [
      {
        id: "components",
        title: "Components and composition",
        summary: "A component is a reusable JavaScript function that returns UI. Composition means building a page from smaller components instead of one large component.",
        points: ["Component names start with a capital letter.", "Keep each component focused on one job.", "A parent can render child components and pass them data."],
        code: `function ArticleCard({ article }) {\n  return (\n    <article>\n      <h2>{article.headline}</h2>\n      <p>{article.subheadline}</p>\n    </article>\n  );\n}`,
        connection: "The news page can be composed from TopicSelector, LevelSelector, ArticleList and ArticleCard. The full article view can add ArticleBody and DiscussionQuestions.",
        question: "Why would ArticleCard be preferable to writing the same article markup twelve times?",
        answer: "It keeps the markup in one reusable place. Each article supplies different data through props, so fixes and design changes only need to be made once.",
        tags: ["component", "composition", "function", "article card"],
      },
      {
        id: "jsx",
        title: "JSX and expressions",
        summary: "JSX lets you describe HTML-like UI inside JavaScript. Curly braces switch from JSX into a JavaScript expression.",
        points: ["Return one enclosing element or a fragment.", "Use className rather than class.", "Put expressions—not statements—inside curly braces."],
        code: `<span className="level-badge">\n  {article.level.toUpperCase()}\n</span>`,
        connection: "JSX will combine Levelled News data such as headline, topic, thumbnail and level into the visual article interface.",
        question: "Why can you use article.headline inside braces but not put an if statement there directly?",
        answer: "article.headline is an expression that produces a value. An if statement controls execution and does not itself produce the value JSX needs.",
        tags: ["jsx", "expression", "className", "curly braces"],
      },
      {
        id: "props",
        title: "Props and one-way data flow",
        summary: "Props are read-only inputs passed from a parent to a child. React data normally flows down the component tree.",
        points: ["Destructure props when it improves readability.", "Do not change a prop inside the child.", "Pass event handlers as props when a child must notify its parent."],
        code: `function LevelButton({ level, selected, onSelect }) {\n  return (\n    <button onClick={() => onSelect(level)}>\n      {selected ? "✓ " : ""}{level.toUpperCase()}\n    </button>\n  );\n}`,
        connection: "A LevelSelector parent can pass each button its level and selection state, while receiving the user's choice through an onSelect callback.",
        question: "If LevelButton needs to change the selected level, where should that state normally live?",
        answer: "In the closest shared parent that needs the value. The parent passes the current value and a callback down to LevelButton.",
        tags: ["props", "data flow", "callback", "parent child"],
      },
      {
        id: "lists-keys",
        title: "Rendering lists and keys",
        summary: "Use map() to turn an array of data into an array of elements. A stable key helps React match each rendered item with its data.",
        points: ["The key must be unique among siblings.", "Prefer a database ID to an array index.", "The key is for React; it is not passed as an ordinary prop."],
        code: `{articles.map((article) => (\n  <ArticleCard key={article.id} article={article} />\n))}`,
        connection: "The headlines endpoint returns a list of SimplifiedArticles. map() can turn those records into ArticleCard components, using the database id as the key.",
        question: "Why is article.id a better key than the array index?",
        answer: "The database ID stays attached to the same article if the list is reordered or filtered. An index can then point to a different item and confuse React's reconciliation.",
        tags: ["map", "list", "key", "array", "reconciliation"],
      },
    ],
  },
  {
    id: "m2",
    number: "02",
    title: "State and interaction",
    subtitle: "Events, useState and state design",
    concepts: [
      {
        id: "events",
        title: "Events and handlers",
        summary: "React event props receive a function to run when an interaction happens. Pass the function; do not call it during rendering.",
        points: ["Use names such as handleLevelChange for local handlers.", "A handler may update state or call a callback prop.", "Wrap a call in an arrow function when you need to pass an argument."],
        code: `<button onClick={() => handleLevelChange("b1")}>\n  B1\n</button>`,
        connection: "Click handlers will change the selected topic or level and can open the article chosen by the learner.",
        question: "What is the difference between onClick={handleClick} and onClick={handleClick()}?",
        answer: "The first passes the function for React to call later. The second calls it immediately during rendering and passes its return value.",
        tags: ["event", "handler", "onClick", "function"],
      },
      {
        id: "usestate",
        title: "useState and re-rendering",
        summary: "useState stores information that must survive renders. Its setter schedules a new render with the updated value.",
        points: ["Hooks must be called at the top level of a component.", "Choose the simplest state that describes the UI.", "State updates are reflected on the next render, not by mutating the current variable."],
        code: `const [level, setLevel] = useState("b1");\n\nfunction handleLevelChange(nextLevel) {\n  setLevel(nextLevel);\n}`,
        connection: "Selected level, selected topic, loading status and the currently open article are all possible pieces of Levelled News UI state.",
        question: "Why would assigning level = 'a2' not be the correct way to update the interface?",
        answer: "It attempts to mutate the current render's variable and does not tell React to render again. setLevel schedules the state update and re-render.",
        tags: ["useState", "state", "setter", "render", "hook"],
      },
      {
        id: "object-state",
        title: "Objects and arrays in state",
        summary: "Treat objects and arrays in state as immutable. Create a replacement using spread, map or filter instead of changing the existing value.",
        points: ["Spread copies the existing top-level properties.", "Functional updates are useful when the next value depends on the previous one.", "Nested data may require copying at more than one level."],
        code: `setFilters((previous) => ({\n  ...previous,\n  level: "b2",\n}));`,
        connection: "Topic and level could be kept in one filters object, although two simple state variables may be clearer for the first Levelled News build.",
        question: "What would be lost if setFilters({ level: 'b2' }) replaces an object that also contains topic?",
        answer: "The topic property would disappear because the setter replaces the object. Spreading the previous object retains unchanged properties.",
        tags: ["object", "array", "immutable", "spread", "functional update"],
      },
      {
        id: "lifting-state",
        title: "Lifting state up",
        summary: "When sibling components need the same changing value, move that state to their nearest shared parent and pass it down.",
        points: ["Keep one source of truth.", "The owner passes values and callbacks to children.", "Do not lift state higher than the components that need it."],
        code: `function NewsPage() {\n  const [level, setLevel] = useState("b1");\n  return <>\n    <LevelSelector value={level} onChange={setLevel} />\n    <ArticleList level={level} />\n  </>;\n}`,
        connection: "NewsPage can own the chosen level so both LevelSelector and ArticleList stay synchronised.",
        question: "What problem can occur if LevelSelector and ArticleList each store their own selected level?",
        answer: "They can disagree, leaving the controls showing one level while the list fetches another. Shared parent state gives one source of truth.",
        tags: ["lifting state", "single source", "siblings", "shared state"],
      },
    ],
  },
  {
    id: "m3",
    number: "03",
    title: "Forms in React",
    subtitle: "Controlled inputs, validation and submission",
    concepts: [
      {
        id: "controlled",
        title: "Controlled inputs",
        summary: "A controlled input gets its current value from React state and reports edits through onChange.",
        points: ["The value prop makes state the source of truth.", "Read event.target.value in the change handler.", "Controlled fields make validation and coordinated UI straightforward."],
        code: `<select value={level} onChange={(event) => setLevel(event.target.value)}>\n  <option value="a1">A1</option>\n  <option value="a2">A2</option>\n  <option value="b1">B1</option>\n  <option value="b2">B2</option>\n</select>`,
        connection: "The backend accepts exactly a1, a2, b1 and b2. A controlled select keeps the displayed choice and the value used in the API URL aligned.",
        question: "What makes this select controlled?",
        answer: "Its value comes from React state, and every user change calls a state setter through onChange.",
        tags: ["form", "controlled", "select", "input", "onChange"],
      },
      {
        id: "uncontrolled",
        title: "Uncontrolled inputs",
        summary: "An uncontrolled input keeps its current value in the DOM. React can read it with a ref when needed.",
        points: ["Useful for simple forms and file inputs.", "defaultValue sets an initial value without controlling later edits.", "Controlled inputs are usually easier when the UI must react to each change."],
        code: `const searchRef = useRef(null);\n\nfunction handleSubmit(event) {\n  event.preventDefault();\n  const term = searchRef.current.value;\n}`,
        connection: "A simple search submitted only when the user presses a button could be uncontrolled, but instant filtering of news cards is better suited to controlled state.",
        question: "Why is a controlled input a better fit for search-as-you-type?",
        answer: "React receives every change in state, so it can immediately derive and render the filtered results.",
        tags: ["uncontrolled", "ref", "defaultValue", "dom", "form"],
      },
      {
        id: "form-submit",
        title: "Submission and validation",
        summary: "A form's onSubmit handles both button clicks and keyboard submission. Prevent the browser's default reload before handling data in React.",
        points: ["Use semantic form and button elements.", "Validate at the appropriate time.", "Show specific, accessible error messages."],
        code: `function handleSubmit(event) {\n  event.preventDefault();\n  if (!topic || !level) return;\n  loadArticles(topic, level);\n}`,
        connection: "A topic-and-level form can validate the selection, then request the matching endpoint without reloading the page.",
        question: "Why put the handler on form.onSubmit rather than only on the button's onClick?",
        answer: "onSubmit covers normal form behaviour, including pressing Enter, and keeps submission logic attached to the semantic form.",
        tags: ["submit", "validation", "preventDefault", "accessible"],
      },
    ],
  },
  {
    id: "m4",
    number: "04",
    title: "Context and advanced state",
    subtitle: "Context, reducers and efficient rendering",
    concepts: [
      {
        id: "context",
        title: "React Context",
        summary: "Context makes a value available to a subtree without passing it through every intermediate component.",
        points: ["Create the context outside components.", "A provider supplies the value.", "Consumers read it with useContext."],
        code: `const PreferencesContext = createContext(null);\n\nfunction PreferencesProvider({ children }) {\n  const [level, setLevel] = useState("b1");\n  return (\n    <PreferencesContext.Provider value={{ level, setLevel }}>\n      {children}\n    </PreferencesContext.Provider>\n  );\n}`,
        connection: "Context could remember a preferred English level across the header, article list and article page. It is unnecessary if only one small parent subtree needs the level.",
        question: "When would props still be preferable to Context?",
        answer: "When the value travels only one or two levels or belongs to a small, clear component relationship. Props keep dependencies explicit.",
        tags: ["context", "provider", "useContext", "prop drilling"],
      },
      {
        id: "context-rendering",
        title: "Context and re-rendering",
        summary: "When a provider value changes, components consuming that context render again. A freshly created object is a new reference on every provider render.",
        points: ["Split unrelated contexts when they change independently.", "React.memo can skip some child renders when props are unchanged.", "useMemo can stabilise a provider object when that optimisation is genuinely needed."],
        code: `const value = useMemo(\n  () => ({ level, setLevel }),\n  [level],\n);`,
        connection: "If Levelled News later has user, theme and language preferences, separate contexts can stop one frequently changing value from notifying unrelated consumers.",
        question: "Why can { level, setLevel } be considered changed even when level is unchanged?",
        answer: "An object literal creates a new object reference during each render. Context compares the value reference, not the individual properties.",
        tags: ["context", "render", "memo", "useMemo", "reference"],
      },
      {
        id: "reducer",
        title: "useReducer",
        summary: "useReducer centralises related state transitions in a reducer function. It is useful when state has several meaningful actions or transitions.",
        points: ["Dispatch describes what happened.", "The reducer returns the next state without mutation.", "Simple independent values often remain clearer with useState."],
        code: `function newsReducer(state, action) {\n  switch (action.type) {\n    case "loading":\n      return { ...state, status: "loading", error: null };\n    case "loaded":\n      return { ...state, status: "success", articles: action.payload };\n    case "failed":\n      return { ...state, status: "error", error: action.payload };\n    default:\n      return state;\n  }\n}`,
        connection: "A reducer can model the Levelled News request lifecycle—idle, loading, success and error—once the data-fetching state becomes complex.",
        question: "What advantage does a 'loaded' action have over several separate setter calls?",
        answer: "It represents one coherent transition and updates the related fields together according to one testable rule.",
        tags: ["useReducer", "reducer", "dispatch", "action", "state machine"],
      },
    ],
  },
  {
    id: "m5",
    number: "05",
    title: "Hooks and API data",
    subtitle: "Effects, fetching and reusable logic",
    concepts: [
      {
        id: "effects",
        title: "useEffect and dependencies",
        summary: "An Effect synchronises a component with something outside React, such as a network request. Dependencies say which reactive values the Effect uses.",
        points: ["Do not use Effects for values you can calculate during rendering.", "Include reactive values used by the Effect.", "Return a cleanup function when the external process needs stopping or undoing."],
        code: `useEffect(() => {\n  loadArticles(topic, level);\n}, [topic, level]);`,
        connection: "Changing topic or level can trigger a request to `/articles/${topic}/${level}`. Both values belong in the dependency array.",
        question: "What stale-data bug could occur if level is omitted from the dependency array?",
        answer: "Changing the level would not rerun the Effect, so the page could continue showing articles fetched for the previous level.",
        tags: ["useEffect", "effect", "dependency", "synchronise"],
      },
      {
        id: "fetching",
        title: "Fetching, loading and errors",
        summary: "Network UI needs to represent more than the returned data: at minimum loading, success, empty and error states.",
        points: ["Check response.ok before reading success data.", "Clear or replace stale errors when a new request starts.", "Abort obsolete requests when selections change quickly."],
        code: `async function getArticles(topic, level, signal) {\n  const url = API_URL + "/articles/" + topic + "/" + level;\n  const response = await fetch(url, { signal });\n  if (!response.ok) throw new Error("Could not load articles");\n  return response.json();\n}`,
        connection: "The FastAPI route either returns a list of saved/generated articles or an HTTP error. The React UI should make every state visible rather than failing silently.",
        question: "Why is a resolved fetch promise not enough to prove the request succeeded?",
        answer: "fetch normally resolves even for HTTP errors such as 404 or 500. You must inspect response.ok or the status code.",
        tags: ["fetch", "api", "loading", "error", "async", "abort"],
      },
      {
        id: "custom-hooks",
        title: "Custom hooks",
        summary: "A custom hook packages reusable stateful logic. Its name starts with use and it may call other hooks.",
        points: ["Extract shared behaviour, not merely a few lines.", "Each call receives its own state.", "Keep rendering in components; keep reusable state logic in the hook."],
        code: `function useArticles(topic, level) {\n  const [result, setResult] = useState({ status: "idle", data: [] });\n  // Effect and request logic live here.\n  return result;\n}`,
        connection: "useArticles can own headline-list fetching while useArticle can fetch a full body from `/article/{article_id}/{level}`.",
        question: "Does using useArticles cause two components to share the same state automatically?",
        answer: "No. Each hook call has independent state. Shared state would need to live in a common owner, Context or an external store/cache.",
        tags: ["custom hook", "reuse", "useArticles", "logic"],
      },
      {
        id: "derived-data",
        title: "Derived data and useMemo",
        summary: "Derived data is calculated from existing props or state. Calculate it during rendering; useMemo is only an optimisation for expensive calculations or stable references.",
        points: ["Do not store filtered results as duplicate state unless necessary.", "Measure before adding memoisation.", "Correct dependencies are essential."],
        code: `const visibleArticles = useMemo(\n  () => articles.filter((article) => article.headline.toLowerCase().includes(search.toLowerCase())),\n  [articles, search],\n);`,
        connection: "Client-side headline search can derive its visible list from fetched articles and the search term, avoiding a second synchronised copy of the list.",
        question: "Why can storing both articles and filteredArticles in state be risky?",
        answer: "They can become inconsistent when one changes without the other. Filtering from the source data keeps a single source of truth.",
        tags: ["derived", "useMemo", "filter", "performance", "single source"],
      },
    ],
  },
  {
    id: "m6",
    number: "06",
    title: "Quality and architecture",
    subtitle: "Accessibility, testing and the first build",
    concepts: [
      {
        id: "accessibility",
        title: "Accessible React interfaces",
        summary: "Use semantic HTML first, then add ARIA only where native elements do not supply the required meaning.",
        points: ["Buttons perform actions; links navigate.", "Every form control needs an accessible label.", "Loading and error messages should be available to assistive technology."],
        code: `<label htmlFor="news-level">Reading level</label>\n<select id="news-level" value={level} onChange={handleChange}>…</select>\n<p role="status">Loading articles…</p>`,
        connection: "English learners need especially clear labels, focus states and feedback. Article thumbnails also need useful alt text or an empty alt when decorative.",
        question: "Why should a clickable div usually be replaced with a button?",
        answer: "A button already provides keyboard operation, focus behaviour and action semantics. A div requires all of that to be recreated correctly.",
        tags: ["accessibility", "semantic", "aria", "label", "keyboard"],
      },
      {
        id: "testing",
        title: "Testing user behaviour",
        summary: "Good component tests interact with the interface as a user would and check visible outcomes rather than internal implementation details.",
        points: ["Query elements by accessible role and name.", "Test loading, success and failure paths.", "Mock the network boundary rather than React internals."],
        code: `render(<LevelSelector value="b1" onChange={handleChange} />);\nawait user.click(screen.getByRole("button", { name: "A2" }));\nexpect(handleChange).toHaveBeenCalledWith("a2");`,
        connection: "Levelled News tests can verify that choosing B1 loads the B1 endpoint, cards display returned headlines, and a failed request shows a useful retry option.",
        question: "Why is getByRole usually preferable to selecting an element by CSS class in a test?",
        answer: "It follows how users and assistive technologies identify the control, while CSS classes are styling details that may change without changing behaviour.",
        tags: ["test", "testing library", "user", "mock", "role"],
      },
      {
        id: "architecture",
        title: "A sensible first Levelled News build",
        summary: "Start with a small vertical slice: choose topic and level, fetch headlines, open one article, and handle loading and errors.",
        points: ["Build with real API shapes early.", "Keep API calls in a small service layer.", "Add Context, reducers and memoisation only when the simpler design shows a real need."],
        code: `App\n└─ NewsPage (topic + level state)\n   ├─ NewsFilters\n   ├─ RequestFeedback\n   └─ ArticleList\n      └─ ArticleCard`,
        connection: "This directly matches the existing two-stage backend: fetch twelve simplified headlines first, then fetch/generate the selected article body by database id and level.",
        question: "Which feature should come later: basic article loading or a global preferences Context? Why?",
        answer: "Basic article loading. It proves the core user journey and reveals what state genuinely needs sharing before introducing a global abstraction.",
        tags: ["architecture", "mvp", "component tree", "api service"],
      },
    ],
  },
];

export const allConcepts = modules.flatMap((module) =>
  module.concepts.map((concept) => ({ ...concept, moduleId: module.id, moduleTitle: module.title })),
);
